export enum ECliOptions {
  TimeTravel = 'time-travel',
  Decode = 'decode',
  Migrate = 'migrate',
  Find = 'find',
  Unification = 'uni',
}

export enum ECliFlags {
  Force = '--force',
  ShortForce = '-f',
  Help = '--help',
  ShortHelp = '-h',
  Path = '--path',
  ShortPath = '-p',
  Value = '--value',
  ShortValue = '-v',
  Keys = '--keys',
  ShortKeys = '-k',
  Ip = '--ip',
  ShortIp = '-ip',
  Json = '--json',
  ShortJson = '-j',
  FormatProto = '-proto',
  FormatJson = '-json',
  Method = '--method',
  ShortMethod = '-m',
  Code = '--code',
  ShortCode = '-c',
  SaveDecoded = '--save',
  ShortSaveDecoded = '-s',
}
